# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('Animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('Animal_species', models.CharField(max_length=100)),
                ('Animal_type', models.CharField(max_length=20)),
                ('Scientific_name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Animal_feed', models.CharField(max_length=100)),
            ],
        ),
    ]
