# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0002_animal_feed_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_name', models.CharField(max_length=200)),
                ('Medicine_cost', models.FloatField(default=0.0)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='Animal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_details.Animal'),
        ),
    ]
