# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0003_auto_20171023_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='Animal_id',
        ),
        migrations.AddField(
            model_name='animal',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
