# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0004_auto_20171023_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='Animal_id',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
