# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0006_auto_20171024_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_name', models.CharField(max_length=200)),
                ('Medicine_cost', models.FloatField(default=0.0)),
                ('Date', models.DateField(auto_now=True)),
                ('Animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_details.Animal')),
            ],
        ),
    ]
